name: C/C++ CI
on:  
  push:  
    branches: [ "main" ]
  pull_request:
      branches: [ "main" ]
    
jobs:  
  build:
    runs-on: ubuntu-latest
    
    steps:
     - uses: actions/checkout@v4
     - name: Install dependencies
       run: |
          sudo apt-get update
          sudo apt-get install -y iperf3 iproute2 jq
     - name: make
       run: make
     - name: Run tests
       run: |
          sudo ./src/tcp_connect_time localhost 80 || true
          sudo ./src/optimize_tcp_params localhost 80 || true
